// <auto-generated>
// Generated by tools/generate_seed.py from data/IAB251_Synthetic_Baggage_Manifest.xlsx.
// Do not edit by hand - change the spreadsheet and re-run the script instead.
// </auto-generated>
using AeroLink.Web.Models;
using Microsoft.EntityFrameworkCore;

namespace AeroLink.Web.Data;

/// <summary>
/// Seed data for flights, bags and baggage exceptions, taken from the supplied synthetic baggage manifest.
/// </summary>
public static class ManifestSeedData
{
    /// <summary>Registers the manifest rows as EF Core seed data on the given model.</summary>
    /// <param name="modelBuilder">The model builder used by <see cref="AppDbContext"/>.</param>
    public static void Apply(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Flight>().HasData(
            new Flight
            {
                FlightId = 101,
                FlightLabel = "A",
                FlightNumber = "DEMO101",
                DepartureAirport = "BNE",
                ArrivalAirport = "SYD",
                ScheduledDepartureUtc = new DateTime(2026, 10, 5, 3, 0, 0, DateTimeKind.Utc),
                AircraftId = "DEMO-AIR-101",
                LoadingStatus = LoadingStatus.NotStarted
            },
            new Flight
            {
                FlightId = 102,
                FlightLabel = "B",
                FlightNumber = "DEMO102",
                DepartureAirport = "BNE",
                ArrivalAirport = "MEL",
                ScheduledDepartureUtc = new DateTime(2026, 10, 5, 3, 30, 0, DateTimeKind.Utc),
                AircraftId = "DEMO-AIR-102",
                LoadingStatus = LoadingStatus.NotStarted
            },
            new Flight
            {
                FlightId = 103,
                FlightLabel = "C",
                FlightNumber = "DEMO103",
                DepartureAirport = "BNE",
                ArrivalAirport = "CBR",
                ScheduledDepartureUtc = new DateTime(2026, 10, 5, 4, 0, 0, DateTimeKind.Utc),
                AircraftId = "DEMO-AIR-103",
                LoadingStatus = LoadingStatus.NotStarted
            },
            new Flight
            {
                FlightId = 104,
                FlightLabel = "D",
                FlightNumber = "DEMO104",
                DepartureAirport = "BNE",
                ArrivalAirport = "CNS",
                ScheduledDepartureUtc = new DateTime(2026, 10, 5, 4, 30, 0, DateTimeKind.Utc),
                AircraftId = "DEMO-AIR-104",
                LoadingStatus = LoadingStatus.NotStarted
            },
            new Flight
            {
                FlightId = 105,
                FlightLabel = "E",
                FlightNumber = "DEMO105",
                DepartureAirport = "BNE",
                ArrivalAirport = "ADL",
                ScheduledDepartureUtc = new DateTime(2026, 10, 5, 5, 0, 0, DateTimeKind.Utc),
                AircraftId = "DEMO-AIR-105",
                LoadingStatus = LoadingStatus.NotStarted
            },
            new Flight
            {
                FlightId = 106,
                FlightLabel = "F",
                FlightNumber = "DEMO106",
                DepartureAirport = "BNE",
                ArrivalAirport = "PER",
                ScheduledDepartureUtc = new DateTime(2026, 10, 5, 5, 30, 0, DateTimeKind.Utc),
                AircraftId = "DEMO-AIR-106",
                LoadingStatus = LoadingStatus.NotStarted
            },
            new Flight
            {
                FlightId = 107,
                FlightLabel = "G",
                FlightNumber = "DEMO107",
                DepartureAirport = "BNE",
                ArrivalAirport = "HBA",
                ScheduledDepartureUtc = new DateTime(2026, 10, 5, 6, 0, 0, DateTimeKind.Utc),
                AircraftId = "DEMO-AIR-107",
                LoadingStatus = LoadingStatus.NotStarted
            },
            new Flight
            {
                FlightId = 108,
                FlightLabel = "H",
                FlightNumber = "DEMO108",
                DepartureAirport = "BNE",
                ArrivalAirport = "DRW",
                ScheduledDepartureUtc = new DateTime(2026, 10, 5, 6, 30, 0, DateTimeKind.Utc),
                AircraftId = "DEMO-AIR-108",
                LoadingStatus = LoadingStatus.NotStarted
            },
            new Flight
            {
                FlightId = 109,
                FlightLabel = "I",
                FlightNumber = "DEMO109",
                DepartureAirport = "BNE",
                ArrivalAirport = "OOL",
                ScheduledDepartureUtc = new DateTime(2026, 10, 5, 7, 0, 0, DateTimeKind.Utc),
                AircraftId = "DEMO-AIR-109",
                LoadingStatus = LoadingStatus.NotStarted
            },
            new Flight
            {
                FlightId = 110,
                FlightLabel = "J",
                FlightNumber = "DEMO101",
                DepartureAirport = "BNE",
                ArrivalAirport = "SYD",
                ScheduledDepartureUtc = new DateTime(2026, 10, 6, 3, 0, 0, DateTimeKind.Utc),
                AircraftId = "DEMO-AIR-110",
                LoadingStatus = LoadingStatus.NotStarted
            });

        modelBuilder.Entity<Bag>().HasData(
            new Bag
            {
                BagId = 1,
                FlightId = 101,
                Tag = "DEMO-101-001",
                HandlingType = HandlingType.Standard,
                HandlingInstruction = "Standard handling.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 2,
                FlightId = 101,
                Tag = "DEMO-101-002",
                HandlingType = HandlingType.Standard,
                HandlingInstruction = "Standard handling.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 3,
                FlightId = 101,
                Tag = "DEMO-101-003",
                HandlingType = HandlingType.Standard,
                HandlingInstruction = "Standard handling.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 4,
                FlightId = 101,
                Tag = "DEMO-101-004",
                HandlingType = HandlingType.Standard,
                HandlingInstruction = "Standard handling.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 5,
                FlightId = 101,
                Tag = "DEMO-101-005",
                HandlingType = HandlingType.Standard,
                HandlingInstruction = "Standard handling.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 6,
                FlightId = 101,
                Tag = "DEMO-101-006",
                HandlingType = HandlingType.Fragile,
                HandlingInstruction = "Handle with care. Keep upright.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 7,
                FlightId = 101,
                Tag = "DEMO-101-007",
                HandlingType = HandlingType.Fragile,
                HandlingInstruction = "Handle with care. Keep upright.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 8,
                FlightId = 101,
                Tag = "DEMO-101-008",
                HandlingType = HandlingType.Oversized,
                HandlingInstruction = "Use the designated oversized baggage area.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 9,
                FlightId = 101,
                Tag = "DEMO-101-009",
                HandlingType = HandlingType.Wheelchair,
                HandlingInstruction = "Handle carefully. Keep supplied parts together.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 10,
                FlightId = 101,
                Tag = "DEMO-101-010",
                HandlingType = HandlingType.SportingEquipment,
                HandlingInstruction = "Keep equipment in its protective case.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 11,
                FlightId = 102,
                Tag = "DEMO-102-001",
                HandlingType = HandlingType.Standard,
                HandlingInstruction = "Standard handling.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 12,
                FlightId = 102,
                Tag = "DEMO-102-002",
                HandlingType = HandlingType.Standard,
                HandlingInstruction = "Standard handling.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 13,
                FlightId = 102,
                Tag = "DEMO-102-003",
                HandlingType = HandlingType.Standard,
                HandlingInstruction = "Standard handling.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 14,
                FlightId = 102,
                Tag = "DEMO-102-004",
                HandlingType = HandlingType.Standard,
                HandlingInstruction = "Standard handling.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 15,
                FlightId = 102,
                Tag = "DEMO-102-005",
                HandlingType = HandlingType.Standard,
                HandlingInstruction = "Standard handling.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 16,
                FlightId = 102,
                Tag = "DEMO-102-006",
                HandlingType = HandlingType.Fragile,
                HandlingInstruction = "Handle with care. Keep upright.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 17,
                FlightId = 102,
                Tag = "DEMO-102-007",
                HandlingType = HandlingType.Fragile,
                HandlingInstruction = "Handle with care. Keep upright.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 18,
                FlightId = 102,
                Tag = "DEMO-102-008",
                HandlingType = HandlingType.Oversized,
                HandlingInstruction = "Use the designated oversized baggage area.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 19,
                FlightId = 102,
                Tag = "DEMO-102-009",
                HandlingType = HandlingType.Wheelchair,
                HandlingInstruction = "Handle carefully. Keep supplied parts together.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 20,
                FlightId = 102,
                Tag = "DEMO-102-010",
                HandlingType = HandlingType.SportingEquipment,
                HandlingInstruction = "Keep equipment in its protective case.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 21,
                FlightId = 103,
                Tag = "DEMO-103-001",
                HandlingType = HandlingType.Standard,
                HandlingInstruction = "Standard handling.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 22,
                FlightId = 103,
                Tag = "DEMO-103-002",
                HandlingType = HandlingType.Standard,
                HandlingInstruction = "Standard handling.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 23,
                FlightId = 103,
                Tag = "DEMO-103-003",
                HandlingType = HandlingType.Standard,
                HandlingInstruction = "Standard handling.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 24,
                FlightId = 103,
                Tag = "DEMO-103-004",
                HandlingType = HandlingType.Standard,
                HandlingInstruction = "Standard handling.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 25,
                FlightId = 103,
                Tag = "DEMO-103-005",
                HandlingType = HandlingType.Standard,
                HandlingInstruction = "Standard handling.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 26,
                FlightId = 103,
                Tag = "DEMO-103-006",
                HandlingType = HandlingType.Standard,
                HandlingInstruction = "Standard handling.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 27,
                FlightId = 103,
                Tag = "DEMO-103-007",
                HandlingType = HandlingType.Standard,
                HandlingInstruction = "Standard handling.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 28,
                FlightId = 103,
                Tag = "DEMO-103-008",
                HandlingType = HandlingType.Standard,
                HandlingInstruction = "Standard handling.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 29,
                FlightId = 103,
                Tag = "DEMO-103-009",
                HandlingType = HandlingType.Standard,
                HandlingInstruction = "Standard handling.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 30,
                FlightId = 103,
                Tag = "DEMO-103-010",
                HandlingType = HandlingType.Standard,
                HandlingInstruction = "Standard handling.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 31,
                FlightId = 104,
                Tag = "DEMO-104-001",
                HandlingType = HandlingType.Standard,
                HandlingInstruction = "Standard handling.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 32,
                FlightId = 104,
                Tag = "DEMO-104-002",
                HandlingType = HandlingType.Standard,
                HandlingInstruction = "Standard handling.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 33,
                FlightId = 104,
                Tag = "DEMO-104-003",
                HandlingType = HandlingType.Standard,
                HandlingInstruction = "Standard handling.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 34,
                FlightId = 104,
                Tag = "DEMO-104-004",
                HandlingType = HandlingType.Standard,
                HandlingInstruction = "Standard handling.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 35,
                FlightId = 104,
                Tag = "DEMO-104-005",
                HandlingType = HandlingType.Standard,
                HandlingInstruction = "Standard handling.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 36,
                FlightId = 104,
                Tag = "DEMO-104-006",
                HandlingType = HandlingType.Fragile,
                HandlingInstruction = "Handle with care. Keep upright.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 37,
                FlightId = 104,
                Tag = "DEMO-104-007",
                HandlingType = HandlingType.Fragile,
                HandlingInstruction = "Handle with care. Keep upright.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 38,
                FlightId = 104,
                Tag = "DEMO-104-008",
                HandlingType = HandlingType.Oversized,
                HandlingInstruction = "Use the designated oversized baggage area.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 39,
                FlightId = 104,
                Tag = "DEMO-104-009",
                HandlingType = HandlingType.Wheelchair,
                HandlingInstruction = "Handle carefully. Keep supplied parts together.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 40,
                FlightId = 104,
                Tag = "DEMO-104-010",
                HandlingType = HandlingType.SportingEquipment,
                HandlingInstruction = "Keep equipment in its protective case.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 41,
                FlightId = 105,
                Tag = "DEMO-105-001",
                HandlingType = HandlingType.Standard,
                HandlingInstruction = "Standard handling.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 42,
                FlightId = 105,
                Tag = "DEMO-105-002",
                HandlingType = HandlingType.Standard,
                HandlingInstruction = "Standard handling.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 43,
                FlightId = 105,
                Tag = "DEMO-105-003",
                HandlingType = HandlingType.Standard,
                HandlingInstruction = "Standard handling.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 44,
                FlightId = 105,
                Tag = "DEMO-105-004",
                HandlingType = HandlingType.Standard,
                HandlingInstruction = "Standard handling.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 45,
                FlightId = 105,
                Tag = "DEMO-105-005",
                HandlingType = HandlingType.Standard,
                HandlingInstruction = "Standard handling.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 46,
                FlightId = 105,
                Tag = "DEMO-105-006",
                HandlingType = HandlingType.Fragile,
                HandlingInstruction = "Handle with care. Keep upright.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 47,
                FlightId = 105,
                Tag = "DEMO-105-007",
                HandlingType = HandlingType.Fragile,
                HandlingInstruction = "Handle with care. Keep upright.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 48,
                FlightId = 105,
                Tag = "DEMO-105-008",
                HandlingType = HandlingType.Oversized,
                HandlingInstruction = "Use the designated oversized baggage area.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 49,
                FlightId = 105,
                Tag = "DEMO-105-009",
                HandlingType = HandlingType.Wheelchair,
                HandlingInstruction = "Handle carefully. Keep supplied parts together.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 50,
                FlightId = 105,
                Tag = "DEMO-105-010",
                HandlingType = HandlingType.SportingEquipment,
                HandlingInstruction = "Keep equipment in its protective case.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 51,
                FlightId = 106,
                Tag = "DEMO-106-001",
                HandlingType = HandlingType.Standard,
                HandlingInstruction = "Standard handling.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 52,
                FlightId = 106,
                Tag = "DEMO-106-002",
                HandlingType = HandlingType.Standard,
                HandlingInstruction = "Standard handling.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 53,
                FlightId = 106,
                Tag = "DEMO-106-003",
                HandlingType = HandlingType.Standard,
                HandlingInstruction = "Standard handling.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 54,
                FlightId = 106,
                Tag = "DEMO-106-004",
                HandlingType = HandlingType.Standard,
                HandlingInstruction = "Standard handling.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 55,
                FlightId = 106,
                Tag = "DEMO-106-005",
                HandlingType = HandlingType.Standard,
                HandlingInstruction = "Standard handling.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 56,
                FlightId = 106,
                Tag = "DEMO-106-006",
                HandlingType = HandlingType.Fragile,
                HandlingInstruction = "Handle with care. Keep upright.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 57,
                FlightId = 106,
                Tag = "DEMO-106-007",
                HandlingType = HandlingType.Fragile,
                HandlingInstruction = "Handle with care. Keep upright.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 58,
                FlightId = 106,
                Tag = "DEMO-106-008",
                HandlingType = HandlingType.Oversized,
                HandlingInstruction = "Use the designated oversized baggage area.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 59,
                FlightId = 106,
                Tag = "DEMO-106-009",
                HandlingType = HandlingType.Wheelchair,
                HandlingInstruction = "Handle carefully. Keep supplied parts together.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 60,
                FlightId = 106,
                Tag = "DEMO-106-010",
                HandlingType = HandlingType.SportingEquipment,
                HandlingInstruction = "Keep equipment in its protective case.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 61,
                FlightId = 107,
                Tag = "DEMO-107-001",
                HandlingType = HandlingType.Standard,
                HandlingInstruction = "Standard handling.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 62,
                FlightId = 107,
                Tag = "DEMO-107-002",
                HandlingType = HandlingType.Standard,
                HandlingInstruction = "Standard handling.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 63,
                FlightId = 107,
                Tag = "DEMO-107-003",
                HandlingType = HandlingType.Standard,
                HandlingInstruction = "Standard handling.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 64,
                FlightId = 107,
                Tag = "DEMO-107-004",
                HandlingType = HandlingType.Standard,
                HandlingInstruction = "Standard handling.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 65,
                FlightId = 107,
                Tag = "DEMO-107-005",
                HandlingType = HandlingType.Standard,
                HandlingInstruction = "Standard handling.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 66,
                FlightId = 107,
                Tag = "DEMO-107-006",
                HandlingType = HandlingType.Fragile,
                HandlingInstruction = "Handle with care. Keep upright.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 67,
                FlightId = 107,
                Tag = "DEMO-107-007",
                HandlingType = HandlingType.Fragile,
                HandlingInstruction = "Handle with care. Keep upright.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 68,
                FlightId = 107,
                Tag = "DEMO-107-008",
                HandlingType = HandlingType.Oversized,
                HandlingInstruction = "Use the designated oversized baggage area.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 69,
                FlightId = 107,
                Tag = "DEMO-107-009",
                HandlingType = HandlingType.Wheelchair,
                HandlingInstruction = "Handle carefully. Keep supplied parts together.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 70,
                FlightId = 107,
                Tag = "DEMO-107-010",
                HandlingType = HandlingType.SportingEquipment,
                HandlingInstruction = "Keep equipment in its protective case.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 71,
                FlightId = 108,
                Tag = "DEMO-108-001",
                HandlingType = HandlingType.Standard,
                HandlingInstruction = "Standard handling.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 72,
                FlightId = 108,
                Tag = "DEMO-108-002",
                HandlingType = HandlingType.Standard,
                HandlingInstruction = "Standard handling.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 73,
                FlightId = 108,
                Tag = "DEMO-108-003",
                HandlingType = HandlingType.Standard,
                HandlingInstruction = "Standard handling.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 74,
                FlightId = 108,
                Tag = "DEMO-108-004",
                HandlingType = HandlingType.Standard,
                HandlingInstruction = "Standard handling.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 75,
                FlightId = 108,
                Tag = "DEMO-108-005",
                HandlingType = HandlingType.Standard,
                HandlingInstruction = "Standard handling.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 76,
                FlightId = 108,
                Tag = "DEMO-108-006",
                HandlingType = HandlingType.Fragile,
                HandlingInstruction = "Handle with care. Keep upright.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 77,
                FlightId = 108,
                Tag = "DEMO-108-007",
                HandlingType = HandlingType.Fragile,
                HandlingInstruction = "Handle with care. Keep upright.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 78,
                FlightId = 108,
                Tag = "DEMO-108-008",
                HandlingType = HandlingType.Oversized,
                HandlingInstruction = "Use the designated oversized baggage area.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 79,
                FlightId = 108,
                Tag = "DEMO-108-009",
                HandlingType = HandlingType.Wheelchair,
                HandlingInstruction = "Handle carefully. Keep supplied parts together.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 80,
                FlightId = 108,
                Tag = "DEMO-108-010",
                HandlingType = HandlingType.SportingEquipment,
                HandlingInstruction = "Keep equipment in its protective case.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 81,
                FlightId = 109,
                Tag = "DEMO-109-001",
                HandlingType = HandlingType.Standard,
                HandlingInstruction = "Standard handling.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 82,
                FlightId = 109,
                Tag = "DEMO-109-002",
                HandlingType = HandlingType.Standard,
                HandlingInstruction = "Standard handling.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 83,
                FlightId = 109,
                Tag = "DEMO-109-003",
                HandlingType = HandlingType.Standard,
                HandlingInstruction = "Standard handling.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 84,
                FlightId = 109,
                Tag = "DEMO-109-004",
                HandlingType = HandlingType.Standard,
                HandlingInstruction = "Standard handling.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 85,
                FlightId = 109,
                Tag = "DEMO-109-005",
                HandlingType = HandlingType.Standard,
                HandlingInstruction = "Standard handling.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 86,
                FlightId = 109,
                Tag = "DEMO-109-006",
                HandlingType = HandlingType.Fragile,
                HandlingInstruction = "Handle with care. Keep upright.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 87,
                FlightId = 109,
                Tag = "DEMO-109-007",
                HandlingType = HandlingType.Fragile,
                HandlingInstruction = "Handle with care. Keep upright.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 88,
                FlightId = 109,
                Tag = "DEMO-109-008",
                HandlingType = HandlingType.Oversized,
                HandlingInstruction = "Use the designated oversized baggage area.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 89,
                FlightId = 109,
                Tag = "DEMO-109-009",
                HandlingType = HandlingType.Wheelchair,
                HandlingInstruction = "Handle carefully. Keep supplied parts together.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 90,
                FlightId = 109,
                Tag = "DEMO-109-010",
                HandlingType = HandlingType.SportingEquipment,
                HandlingInstruction = "Keep equipment in its protective case.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 91,
                FlightId = 110,
                Tag = "DEMO-110-001",
                HandlingType = HandlingType.Standard,
                HandlingInstruction = "Standard handling.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 92,
                FlightId = 110,
                Tag = "DEMO-110-002",
                HandlingType = HandlingType.Standard,
                HandlingInstruction = "Standard handling.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 93,
                FlightId = 110,
                Tag = "DEMO-110-003",
                HandlingType = HandlingType.Standard,
                HandlingInstruction = "Standard handling.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 94,
                FlightId = 110,
                Tag = "DEMO-110-004",
                HandlingType = HandlingType.Standard,
                HandlingInstruction = "Standard handling.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 95,
                FlightId = 110,
                Tag = "DEMO-110-005",
                HandlingType = HandlingType.Standard,
                HandlingInstruction = "Standard handling.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 96,
                FlightId = 110,
                Tag = "DEMO-110-006",
                HandlingType = HandlingType.Fragile,
                HandlingInstruction = "Handle with care. Keep upright.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 97,
                FlightId = 110,
                Tag = "DEMO-110-007",
                HandlingType = HandlingType.Fragile,
                HandlingInstruction = "Handle with care. Keep upright.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 98,
                FlightId = 110,
                Tag = "DEMO-110-008",
                HandlingType = HandlingType.Oversized,
                HandlingInstruction = "Use the designated oversized baggage area.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 99,
                FlightId = 110,
                Tag = "DEMO-110-009",
                HandlingType = HandlingType.Wheelchair,
                HandlingInstruction = "Handle carefully. Keep supplied parts together.",
                Outcome = BagOutcome.Pending
            },
            new Bag
            {
                BagId = 100,
                FlightId = 110,
                Tag = "DEMO-110-010",
                HandlingType = HandlingType.SportingEquipment,
                HandlingInstruction = "Keep equipment in its protective case.",
                Outcome = BagOutcome.Pending
            });

        // FlightId is taken from the bag (the spreadsheet lists exception 6 against the wrong flight),
        // and DecisionReason is left empty because every seeded exception is still Open.
        modelBuilder.Entity<BaggageException>().HasData(
            new BaggageException
            {
                ExceptionId = 1,
                BagId = 20,
                FlightId = 102,
                Category = ExceptionCategory.MissingBag,
                Description = "Expected bag not found in the loading area.",
                Status = ExceptionStatus.Open,
                ReportedAtUtc = new DateTime(2026, 10, 5, 2, 0, 0, DateTimeKind.Utc)
            },
            new BaggageException
            {
                ExceptionId = 2,
                BagId = 36,
                FlightId = 104,
                Category = ExceptionCategory.DamagedBag,
                Description = "Visible tear in the bag cover before loading.",
                Status = ExceptionStatus.Open,
                ReportedAtUtc = new DateTime(2026, 10, 5, 2, 0, 0, DateTimeKind.Utc)
            },
            new BaggageException
            {
                ExceptionId = 3,
                BagId = 50,
                FlightId = 105,
                Category = ExceptionCategory.MissingBag,
                Description = "Expected bag not located after the loading-area check.",
                Status = ExceptionStatus.Open,
                ReportedAtUtc = new DateTime(2026, 10, 5, 2, 0, 0, DateTimeKind.Utc)
            },
            new BaggageException
            {
                ExceptionId = 4,
                BagId = 69,
                FlightId = 107,
                Category = ExceptionCategory.MissingBag,
                Description = "Bag not found during the initial loading-area check.",
                Status = ExceptionStatus.Open,
                ReportedAtUtc = new DateTime(2026, 10, 5, 2, 0, 0, DateTimeKind.Utc)
            },
            new BaggageException
            {
                ExceptionId = 5,
                BagId = 80,
                FlightId = 108,
                Category = ExceptionCategory.DamagedBag,
                Description = "Protective case damaged before loading confirmation.",
                Status = ExceptionStatus.Open,
                ReportedAtUtc = new DateTime(2026, 10, 5, 2, 0, 0, DateTimeKind.Utc)
            },
            new BaggageException
            {
                ExceptionId = 6,
                BagId = 11,
                FlightId = 102,
                Category = ExceptionCategory.MissingBag,
                Description = "Expected bag not found in the loading area.",
                Status = ExceptionStatus.Open,
                ReportedAtUtc = new DateTime(2026, 10, 5, 2, 0, 0, DateTimeKind.Utc)
            });
    }
}
