"""Regenerates src/AeroLink.Web/Data/ManifestSeedData.cs from data/IAB251_Synthetic_Baggage_Manifest.xlsx.

Run from the repo root:  python tools/generate_seed.py   (needs: pip install pandas openpyxl)
After regenerating, delete aerolink.db so the database is rebuilt with the new seed.
"""
import pandas as pd
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
XLSX = ROOT / "data" / "IAB251_Synthetic_Baggage_Manifest.xlsx"
OUT = ROOT / "src" / "AeroLink.Web" / "Data" / "ManifestSeedData.cs"

# Fixed timestamp for seeded exceptions (HasData needs constant values).
SEED_REPORTED = "new DateTime(2026, 10, 5, 2, 0, 0, DateTimeKind.Utc)"


def cs(s):
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def dt(t):
    t = pd.Timestamp(t)
    return f"new DateTime({t.year}, {t.month}, {t.day}, {t.hour}, {t.minute}, {t.second}, DateTimeKind.Utc)"


x = pd.ExcelFile(XLSX)
flights = x.parse("Flights")
bags = x.parse("Bags")
exceptions = x.parse("Exceptions")
bag_flight = dict(zip(bags.BagId, bags.FlightId))

lines = []
w = lines.append
w("// <auto-generated>")
w("// Generated by tools/generate_seed.py from data/IAB251_Synthetic_Baggage_Manifest.xlsx.")
w("// Do not edit by hand - change the spreadsheet and re-run the script instead.")
w("// </auto-generated>")
w("using AeroLink.Web.Models;")
w("using Microsoft.EntityFrameworkCore;")
w("")
w("namespace AeroLink.Web.Data;")
w("")
w("/// <summary>")
w("/// Seed data for flights, bags and baggage exceptions, taken from the supplied synthetic baggage manifest.")
w("/// </summary>")
w("public static class ManifestSeedData")
w("{")
w("    /// <summary>Registers the manifest rows as EF Core seed data on the given model.</summary>")
w("    /// <param name=\"modelBuilder\">The model builder used by <see cref=\"AppDbContext\"/>.</param>")
w("    public static void Apply(ModelBuilder modelBuilder)")
w("    {")
w("        modelBuilder.Entity<Flight>().HasData(")
rows = []
for _, r in flights.iterrows():
    rows.append(
        f"            new Flight\n"
        f"            {{\n"
        f"                FlightId = {r.FlightId},\n"
        f"                FlightLabel = {cs(r.FlightLabel)},\n"
        f"                FlightNumber = {cs(r.FlightNumber)},\n"
        f"                DepartureAirport = {cs(r.DepartureAirport)},\n"
        f"                ArrivalAirport = {cs(r.ArrivalAirport)},\n"
        f"                ScheduledDepartureUtc = {dt(r.ScheduledDepartureUtc)},\n"
        f"                AircraftId = {cs(r.AircraftId)},\n"
        f"                LoadingStatus = LoadingStatus.{r.LoadingStatus}\n"
        f"            }}")
w(",\n".join(rows) + ");")
w("")
w("        modelBuilder.Entity<Bag>().HasData(")
rows = []
for _, r in bags.iterrows():
    rows.append(
        f"            new Bag\n"
        f"            {{\n"
        f"                BagId = {r.BagId},\n"
        f"                FlightId = {r.FlightId},\n"
        f"                Tag = {cs(r.Tag.strip())},\n"
        f"                HandlingType = HandlingType.{r.HandlingType},\n"
        f"                HandlingInstruction = {cs(r.HandlingInstruction)},\n"
        f"                Outcome = BagOutcome.{r.Outcome}\n"
        f"            }}")
w(",\n".join(rows) + ");")
w("")
w("        // FlightId is taken from the bag (the spreadsheet lists exception 6 against the wrong flight),")
w("        // and DecisionReason is left empty because every seeded exception is still Open.")
w("        modelBuilder.Entity<BaggageException>().HasData(")
rows = []
for _, r in exceptions.iterrows():
    rows.append(
        f"            new BaggageException\n"
        f"            {{\n"
        f"                ExceptionId = {r.ExceptionId},\n"
        f"                BagId = {r.BagId},\n"
        f"                FlightId = {bag_flight[r.BagId]},\n"
        f"                Category = ExceptionCategory.{r.Category},\n"
        f"                Description = {cs(r.Description)},\n"
        f"                Status = ExceptionStatus.{r.Status},\n"
        f"                ReportedAtUtc = {SEED_REPORTED}\n"
        f"            }}")
w(",\n".join(rows) + ");")
w("    }")
w("}")
OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"Wrote {OUT}")
